### ISSUE TITLE
Not working in graphql 1.10.0 

### ISSUE THREAD

**Issue by gastonmorixe** [Envek/graphql-anycable#5] opened 2020-01-23 14:08 UTC
I just created why here rmosolgo/graphql-ruby#2692

**Comment by Envek** [comment] 2020-01-23 14:14
Oh, that's unfortunate. I will investigate how to work around it the next week. Thank you for the report!

**Comment by gastonmorixe** [comment] 2020-01-23 14:35
@Envek pushed a PR, works for me but it's not clean, let me know your thoughts! thanks

**Comment by gastonmorixe** [comment] 2020-01-30 18:33
I ended up not using this because it's hard to set up in Heroku but I hope it helps to fix this issue.

**Comment by Envek** [comment] 2020-02-04 18:15
I tried to upgrade one of my application to GraphQL-Ruby 1.10 and it works well _without any changes to graphql-anycable_. Can you please share how do you use your subscriptions and what isn't working?

Namely:
 - Do you use interpreter runtime of graphql gem?
 - Do you use [subscription classes](https://graphql-ruby.org/subscriptions/subscription_classes.html)?
 - How is your `GraphqlChannel` looks like?

I will try to reproduce and investigate further.

**Comment by gastonmorixe** [comment] 2020-02-11 00:17
I used the new interpreter/runtime.

**Comment by Envek** [comment] 2020-02-19 15:15
Have you added following `extend` to your root `Subscription` type?

```ruby
extend GraphQL::Subscriptions::SubscriptionRoot
```

As per https://github.com/rmosolgo/graphql-ruby/issues/2727#issuecomment-584870542

**Comment by Envek** [comment] 2020-03-19 13:39
When I started to add testing for interpreter runtime, specs failed.

What is helped to fix them is to redefine subscription resolver methods as per https://github.com/rmosolgo/graphql-ruby/issues/2754#issuecomment-587557702

```ruby
class SubscriptionType < GraphQL::Schema::Object
  extend GraphQL::Subscriptions::SubscriptionRoot

  field :product_created, Product, null: false, resolver_method: :default_resolver
  field :product_updated, Product, null: false, resolver_method: :default_resolver

  def default_resolver
    return object if context.query.subscription_update?

    context.skip
  end
end
```

**Comment by Envek** [comment] 2020-08-24 12:01
Closing as it works in production apps and tests also pass. If you find any issues, feel free to open new issue with reproduction steps, schema and so on.

**Closed as completed by Envek** 2020-08-24 12:01 UTC
